const PDFDoc = require('pdfkit');
const { getSettings } = require('./settings');
const { drawPdfLogo, getPdfThemeTokens } = require('./pdfBranding');

const MONTHS = [
  'January','February','March','April','May','June',
  'July','August','September','October','November','December',
];

function formatMoney(currency, amount) {
  return `${currency} ${Number(amount || 0).toFixed(2)}`;
}

function paymentReceiptCode(payment) {
  return `RCP-${payment.period_year}${String(payment.period_month).padStart(2, '0')}-${String(payment.id).padStart(6, '0')}`;
}

function paymentVerificationCode(payment) {
  return `VER-${String(payment.id).padStart(6, '0')}-${payment.period_year}${String(payment.period_month).padStart(2, '0')}`;
}

function renderPaymentReceiptPdf({ res, payment, duplicateCopy = false }) {
  const settings = getSettings();
  const currency = settings.currency || 'RM';
  const receiptCode = paymentReceiptCode(payment);
  const verificationCode = paymentVerificationCode(payment);
  const palette = getPdfThemeTokens(settings.theme);

  const filename = `Receipt_${receiptCode}.pdf`;
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', 'application/pdf');

  const doc = new PDFDoc({ margin: 50, size: 'A4' });
  doc.pipe(res);

  const schoolName = settings.school_name || 'School';
  const subtitle = settings.subtitle || '';
  const contactBlock = settings.contact_block || '';
  const paidDate = payment.paid_date;
  const periodLabel = `${MONTHS[payment.period_month - 1]} ${payment.period_year}`;

  doc.rect(0, 0, doc.page.width, doc.page.height).fill(palette.pageBg);
  doc.rect(0, 0, doc.page.width, 88).fill(palette.header);
  const titleX = drawPdfLogo(doc, settings.logo_url, { x: 50, y: 18, size: 46, background: palette.pageBg }) || 50;
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text(schoolName, titleX, 22);
  doc.font('Helvetica').fontSize(11).text(subtitle || 'Payment Receipt', titleX, 48);
  doc.font('Helvetica-Bold').fontSize(13).text('OFFICIAL FEE PAYMENT RECEIPT', titleX, 65);

  doc.fillColor(palette.text);
  let y = 108;
  doc.save();
  doc.roundedRect(50, 95, doc.page.width - 100, 4, 2).fill(palette.accent);
  doc.restore();

  if (duplicateCopy) {
    doc.save();
    doc.rotate(-30, { origin: [doc.page.width / 2, doc.page.height / 2] });
    doc.fillColor(palette.watermark).opacity(0.16).font('Helvetica-Bold').fontSize(72)
      .text('DUPLICATE COPY', 65, 360, { align: 'center', width: doc.page.width - 130 });
    doc.restore();
    doc.fillColor(palette.text).opacity(1);
  }

  doc.roundedRect(50, y, doc.page.width - 100, 120, 8).fillAndStroke(palette.cardBg, palette.cardBorder);
  doc.fillColor(palette.text).font('Helvetica-Bold').fontSize(11).text('Receipt Information', 64, y + 14);
  doc.font('Helvetica').fontSize(10)
    .text(`Receipt No: ${receiptCode}`, 64, y + 38)
    .text(`Verification Code: ${verificationCode}`, 64, y + 56)
    .text(`Payment Date: ${paidDate}`, 64, y + 74)
    .text(`Payment Period: ${periodLabel}`, 64, y + 92);
  doc.font('Helvetica').fontSize(10)
    .text(`Method: ${String(payment.method || 'cash').replace('_', ' ').toUpperCase()}`, 320, y + 38)
    .text(`Received By: ${payment.received_by_name || 'N/A'}`, 320, y + 56)
    .text(`Amount Paid: ${formatMoney(currency, payment.amount)}`, 320, y + 74);

  y += 145;
  doc.roundedRect(50, y, doc.page.width - 100, 145, 8).fillAndStroke(palette.cardBg, palette.cardBorder);
  doc.fillColor(palette.text).font('Helvetica-Bold').fontSize(11).text('Payer Details', 64, y + 14);
  doc.font('Helvetica').fontSize(10)
    .text(`Student: ${payment.student_name}`, 64, y + 40)
    .text(`Coverage Month/Year: ${periodLabel}`, 64, y + 58)
    .text(`Notes: ${payment.notes || '—'}`, 64, y + 76, { width: doc.page.width - 130 });

  y += 170;
  doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor(palette.cardBorder).stroke();
  y += 12;
  doc.fillColor(palette.muted).font('Helvetica').fontSize(9)
    .text(contactBlock || 'Contact information is configured in Settings.', 50, y, { width: doc.page.width - 100, align: 'left' });
  y += 30;
  doc.text(settings.report_footer_text || 'Generated by SchoolOps', 50, y, { width: doc.page.width - 100, align: 'center' });

  doc.end();
}

module.exports = {
  paymentReceiptCode,
  paymentVerificationCode,
  renderPaymentReceiptPdf,
};
