const { db } = require('../db/database');

const DEFAULT_SETTINGS = {
  school_name: 'SchoolOps',
  subtitle: 'Finance & Operations Management',
  report_footer_text: 'Generated by SchoolOps',
  currency: 'RM',
  contact_block: '',
  logo_url: '',
  theme: 'classic',
  last_backup_at: '',
};

function ensureSettingsTable() {
  db.exec(`
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `);
}

function initializeDefaultSettings() {
  ensureSettingsTable();

  const insert = db.prepare(`
    INSERT INTO settings (key, value)
    VALUES (?, ?)
    ON CONFLICT(key) DO NOTHING
  `);

  const tx = db.transaction(() => {
    Object.entries(DEFAULT_SETTINGS).forEach(([key, value]) => insert.run(key, value));
  });

  tx();
}

function getSettings() {
  ensureSettingsTable();
  const rows = db.prepare('SELECT key, value FROM settings').all();
  const merged = { ...DEFAULT_SETTINGS };
  for (const row of rows) merged[row.key] = row.value;
  return merged;
}

function updateSettings(changes) {
  ensureSettingsTable();
  const allowed = ['school_name', 'subtitle', 'report_footer_text', 'currency', 'contact_block', 'logo_url', 'theme', 'last_backup_at'];

  const upsert = db.prepare(`
    INSERT INTO settings (key, value, updated_at)
    VALUES (?, ?, datetime('now'))
    ON CONFLICT(key) DO UPDATE SET
      value = excluded.value,
      updated_at = datetime('now')
  `);

  const tx = db.transaction(() => {
    for (const key of allowed) {
      if (Object.prototype.hasOwnProperty.call(changes, key)) {
        upsert.run(key, String(changes[key] ?? ''));
      }
    }
  });

  tx();
  return getSettings();
}

function touchLastBackup(isoString) {
  return updateSettings({ last_backup_at: isoString || new Date().toISOString() });
}

module.exports = {
  DEFAULT_SETTINGS,
  initializeDefaultSettings,
  getSettings,
  updateSettings,
  touchLastBackup,
};
